
# handles connections at low level
events {
    worker_connections 1024;
}

# handles HTTP and HTTPS trafics
http {
    include /etc/nginx/mime.types; # that tells Nginx what kind of content different file extensions are
    default_type application/octet-stream; # if file's type not found in mime.types uset this

	# Defines a virtual server
	# You can have multiple server blocks for multiple websites on one Nginx instance
    server {
		# listen on port 443 (HTTPS) for IPv4 connections, and treat all traffic as SSL encrypted
        listen 443 ssl;
		# Same thing but for IPv6 connections
        listen [::]:443 ssl;

        # The _ is a wildcard/catch-all. It means "respond to any hostname."  
        server_name _;

        # This is the public part it's what Nginx sends to browsers to prove who it is and enable encryption
        ssl_certificate /etc/nginx/ssl/nginx.crt;
        # The path to the private key file that pairs with the certificate.
        ssl_certificate_key /etc/nginx/ssl/nginx.key;
        # Only allow TLS version 1.2 and 1.3. Older versions like TLS 1.0 and 1.1 have known security vulnerabilities
        ssl_protocols TLSv1.2 TLSv1.3;
        # Controls which encryption algorithms are allowed during the SSL handshake
        ssl_ciphers HIGH:!aNULL:!MD5;

        # Root directory the folder where Nginx looks for website files.
        root /var/www/html;
        index index.php index.html index.htm;

        # handles every request (the / matches anything).
        location / {
            try_files $uri $uri/ /index.php?$args;
        }

        # handles any URL that ends in .php
        location ~ \.php$ {
            # Nginx is a web server it's great at serving files and handling connections,
            # but it cannot execute PHP code.
            # PHP is a completely separate program.
            # FastCGI is a protocol that lets Nginx hand off requests to an external program that *can* run PHP.
            fastcgi_pass wordpress:9000; # PHP-FPM listens on 9000 inside wordpress container
            fastcgi_index index.php;
            # This loads a standard file /etc/nginx/fastcgi_params contain params
            include fastcgi_params;
            # it tells PHP-FPM the full path of the file to execute.
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            # PATH_INFO is the part of a URL that comes after the PHP filename
            fastcgi_param PATH_INFO $fastcgi_path_info;
        }

        # Deny access to .htaccess files
        # .htaccess is a configuration file used by Apache 
        # Nginx doesn't use .htaccess at all But the file still exists in the WordPress folder 
        location ~ /\.ht {
            # It tells Nginx to return a 403 Forbidden response to anyone requesting these files
            deny all;
        }
    }
}
