
# handles connections at low level
events {
    worker_connections 1024;
}

# handles HTTP and HTTPS trafics
http {
    include /etc/nginx/mime.types; # that tells Nginx what kind of content different file extensions are
    default_type application/octet-stream; # if file's type not found in mime.types uset this

	# Defines a virtual server
	# You can have multiple server blocks for multiple websites on one Nginx instance
    server {
		# listen on port 443 (HTTPS) for IPv4 connections, and treat all traffic as SSL encrypted
        listen 443 ssl;
		# Same thing but for IPv6 connections
        listen [::]:443 ssl;
        
        server_name _;

        # SSL Configuration
        ssl_certificate /etc/nginx/ssl/nginx.crt;
        ssl_certificate_key /etc/nginx/ssl/nginx.key;
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers HIGH:!aNULL:!MD5;

        # Root directory
        root /var/www/html;
        index index.php index.html index.htm;

        location / {
            try_files $uri $uri/ /index.php?$args;
        }

        # PHP processing
        location ~ \.php$ {
            fastcgi_pass wordpress:9000;
            fastcgi_index index.php;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_param PATH_INFO $fastcgi_path_info;
        }

        # Deny access to .htaccess files
        location ~ /\.ht {
            deny all;
        }
    }
}
